version: "3.3"

services:
  php:
    build: .
    container_name: php
    tty: true
    volumes:
      - ./:/usr/src/app:rw,cached
      - /usr/src/app/vendor
    working_dir: /usr/src/app
    environment:
      XDEBUG_CONFIG: 
        remote_host=${XDEBUG_REMOTE_HOST}
        remote_enable=1
        remote_port=9000
        remote_default_enable=1
        remote_connect_back=0
